name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: bun install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: bunx nx affected -t lint typecheck build
      - run: bun run typecheck:spec
      - run: bun test
      - run: bun run readme-check
      - run: bun run type-contract-check
